config/routes.rb
Rails.application.routes.draw do
  root 'my_files#index'
  resources :my_files
  devise_for :users, controllers: { registrations: 'users/registrations'}

end

app/models/my_file.rb
class MyFile < ActiveRecord::Base
  mount_uploader :local_file, LocalUploader
  mount_uploader :s3_file, S3Uploader

  belongs_to :user

  validates :user_id, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  VALID_PHONE_NUM_REGEX = /01[0|1|6|7|8|9]{1}(\d{4})(\d{4})/
  validates :phone_number, {
      presence: true,
      length: { is: 11 },
      uniqueness: true,
      format: { with: VALID_PHONE_NUM_REGEX }
  }
  
  has_many :my_files
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/my_files_controller.rb
class MyFilesController < ApplicationController
  before_action :set_my_file, only: [:show, :edit, :update, :destroy]
  def new
    @my_file = MyFile.new
  end

  def create
    input_file = my_file_params[:input_file]

    @my_file = MyFile.new
    @my_file.db_file = Base64.encode64 input_file.read
    @my_file.s3_file = @my_file.local_file = input_file
    @my_file.user_id = my_file_params[:user_id]
    @my_file.save
    redirect_to @my_file

  end

  def show
  end

  def index
    @my_files = MyFile.all
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_file
      @my_file = MyFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_file_params
      params.require(:my_file).permit(:input_file, :user_id)
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:phone_number])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_files_helper.rb
module MyFilesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'Bucket-APP', root_path, class: 'navbar-brand' %>
    </div>
    <ul class="nav navbar-nav">
      <% if user_signed_in? %>
          <li><%= link_to 'Show My Files', my_files_path %></li>
          <li><%= link_to 'Save New File', new_my_file_path %></li>
          <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
      <% else %>
          <li><%= link_to 'Log in', new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BucketAppNow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/my_files/_form.html.erb
<%= form_for(@my_file, html: { multipart: true }) do |f| %>
  <% if @my_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@my_file.errors.count, "error") %> prohibited this my_file from being saved:</h2>

      <ul>
      <% @my_file.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.file_field :input_file %>
    <%= f.submit %>
<% end %>

app/views/my_files/edit.html.erb
<h1>Editing My File</h1>

<%= render 'form' %>

<%= link_to 'Show', @my_file %> |
<%= link_to 'Back', my_files_path %>

app/views/my_files/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing My Files</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_files.each do |my_file| %>
      <tr>
        <td><%= link_to 'Show', my_file %></td>
        <td><%= link_to 'Edit', edit_my_file_path(my_file) %></td>
        <td><%= link_to 'Destroy', my_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New My file', new_my_file_path %>

app/views/my_files/new.html.erb
<h1>New My File</h1>

<%= render 'form' %>

<%= link_to 'Back', my_files_path %>

app/views/my_files/show.html.erb
<p id="notice"><%= notice %></p>

<image src="data:image/png;base64, <%= @my_file.db_file %>" />
<%= image_tag image_path @my_file.local_file %>

<%= link_to 'Edit', edit_my_file_path(@my_file) %> |
<%= link_to 'Back', my_files_path %>